FROM node:22-bookworm-slim AS builder

WORKDIR /app
ENV CI=true
ENV HUSKY=0

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json

RUN npm ci

COPY . .

RUN npm run db:generate --workspace=apps/api
RUN npm run build:api

FROM node:22-bookworm-slim AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV API_PORT=4000
ENV HUSKY=0

COPY --from=builder /app /app

EXPOSE 4000

CMD ["node", "apps/api/dist/main.js"]